id: AAC104700
base_file: fD3B7.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:16:27.734803
  last_modified_at: 2022-06-11 13:16:27.734812
